<html><head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <title>Menu Inc</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="styles.css" rel="stylesheet">

        <nav>
            <ul>
                <li><a href="task1.php">Task 1</a></li>
                <li><a href="task2.php">Task 2</a></li>
                <li><a href="task3.php">Task 3</a></li>
                <li><a href="task4.php">Task 4</a></li>
                <li><a href="task5.php">Task 5</a></li>
                <li><a href="task6.php">Task 6</a></li>
                <li><a href="task7.php">Task 7</a></li>
                <li><a href="task8.php">Task 8</a></li>
                <li><a href="task9.php">Task 9</a></li>
            </ul>
        </nav>
</body>
</html>